name: Pipeline

on:
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]


jobs:
  build_test:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      memcached:
        image: public.br5.tech/memcached
        ports:
          - 11211/tcp

      statika:
        image: raver119/statika
        env:
          STATIKA_PORT: 9191
          MASTER_KEY: TEST_MASTER_KEY
          UPLOAD_KEY: TEST_UPLOAD_KEY
          ROOT_DIR: /tmp
          MEMCACHED_HOST: memcached
        ports:
          - 9191/tcp

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Sleep
        run: /usr/bin/sleep 30s

      - name: NC time
        run: printf "GET / HTTP/1.0\r\n\r\n" | nc statika 9191

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build action
        run: yarn build

      - name: Run tests
        env:
          STATIKA_HOST: statika
          STATIKA_PORT: 9191
          UPLOAD_KEY: TEST_UPLOAD_KEY
        run: yarn test


